#!/usr/bin/ruby

#module Config
   #ShareDir = '/usr/share/ruby-commander/'
   #LibDir = '/usr/lib/ruby/1.8/ruby-commander/'
#end

module Config
   ShareDir = '/home/jsaak/svn/jsaak/commander/'
   LibDir = '/home/jsaak/svn/jsaak/commander/'
end

$: << Config::LibDir
require 'commander.rb'

App.new.run
